import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './Sidebar/Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		<body className={inter.className}>
			<main className="page sm:flex sm:flex-row h-screen">
				<Sidebar />
				{children}
			</main>
		</body>
		</html>
	)
}
