import './globals.css'
import Sidebar from './Sidebar/Sidebar'
import { Rubik } from 'next/font/google'

const rubik = Rubik ({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={rubik.className}>
			<body>
				<main className="page sm:flex sm:flex-row h-screen">
					<Sidebar />
					{children}
				</main>
			</body>
		</html>
	)
}
